name: Revelation Games
favicon: null
layout_spectrum: 0.051660649478435516
typography_spectrum: 0.03788052499294281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.05521935597062111
  lightness: 0.795259908773005
  saturation: 0.7569402733352035
  rhythmicContrast: 0.5577695940155536
purpose: []
