name: Revelation Games
favicon: null
layout_spectrum: 0.07774
typography_spectrum: 0.08742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e5e9e8'
    - '#516361'
    - '#284141'
    - '#849492'
  brandStrength: 0.6875
  lightness: 0.795259908773005
  saturation: 0.7569402733352035
  rhythmicContrast: 0.5577695940155536
purpose: []
